# Use our custom template for PHP & WordPress.
image:
  file: .gitpod.Dockerfile

# What ports should be exposed to the user
# https://www.gitpod.io/docs/config-ports/.
ports:
  - port: 8080 # NGINX (WordPress, PMA, MailHog UI)
  - port: 8081 # Database (via phpMyAdmin).
  - port: 8082 # Mailhog GUI.

# The tasks to run inside the container.
# Init    - Run and cached to speed up subsequent Gitpod setups.
# Command -  Runs each time the pod starts.
# https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Compose Helpers
    init: docker-compose pull
    command: docker-compose up
  - name: WordPress Host
    command: |
      wp core download
      wp config create --dbname="wp_gitpod" --dbuser="root" --dbpass="password" --dbhost="127.0.0.1"
      echo "Sleeping for a min while we wait for MySQL to finish setup."
      sleep 60s
      wp core install --url="$(gp url 8080)" --title="Gitpod" --admin_user="admin" --admin_password="password" --admin_email="code@example.com" --skip-email
      wp server

