# Use our custom template for PHP & WordPress.
image:
  file: .gitpod.Dockerfile

# What ports should be exposed to the user
# https://www.gitpod.io/docs/config-ports/.
ports:
- port: 8080 # NGINX (WordPress, PMA, MailHog UI)
- port: 8081 # Database (via phpMyAdmin).
- port: 8082 # Mailhog GUI.

# The tasks to run inside the container.
# Init    - Run and cached to speed up subsequent Gitpod setups.
# Command -  Runs each time the pod starts.
# https://www.gitpod.io/docs/config-start-tasks/
tasks:
- name: WordPress Host
  init: echo "init"
  command: echo "outit"
- name: Compose Helpers
  init: docker-compose pull
  command: docker-compose up
