version: '3.6'
services:
  db:
    image: docker.io/library/mariadb:10.5.15
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wp_gitpod
  db_pma:
    image: docker.io/phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_USER: root
      PMA_PASSWORD: password
  mail:
    image: docker.io/mailhog/mailhog:latest
    ports:
    - 8082:8025
    - 1025:1025
